// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"example.com/pulumi-azure-app-config/sdk/go/azure-app-config/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetItsasecret(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azure-app-config:itsasecret")
}
