// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureAppConfig
{
    [AzureAppConfigResourceType("azure-app-config:index:ConfigResource")]
    public partial class ConfigResource : global::Pulumi.CustomResource
    {
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a ConfigResource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConfigResource(string name, ConfigResourceArgs args, CustomResourceOptions? options = null)
            : base("azure-app-config:index:ConfigResource", name, args ?? new ConfigResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConfigResource(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("azure-app-config:index:ConfigResource", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConfigResource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConfigResource Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ConfigResource(name, id, options);
        }
    }

    public sealed class ConfigResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public ConfigResourceArgs()
        {
        }
        public static new ConfigResourceArgs Empty => new ConfigResourceArgs();
    }
}
